---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-test
spec:
  description: |
    Pipeline for checking pod health.
  tasks:
    - name: task-test
      taskRef:
        name: task-test
        ##