---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-tester
  namespace: cvc-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-tester
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - expose
  - patch
- apiGroups:
  - apps
  resources:
  - namespaces
  - pods
  - services
  - endpoints
  - pods
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - expose
  - patch
- apiGroups:
  - tekton.dev
  resources:
  - "*"
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - nginx
  resources:
  - "*"
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - policy
  resourceNames:
  - tekton-pipelines
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - k8s.nginx.org
  resources:
  - virtualservers
  - virtualserverroutes
  verbs:
  - list
  - watch
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-tester
subjects:
- kind: ServiceAccount
  name: tekton-tester
  namespace: cvc-testing
roleRef:
  kind: ClusterRole
  name: tekton-tester
  apiGroup: rbac.authorization.k8s.io